apiVersion: v1
kind: Service
metadata:
  name: mcode-site
spec:
  type: NodePort
  selector:
    app: mcode-site
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
#   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcode-site
spec:
  selector:
    matchLabels:
      app: mcode-site
  replicas: 2
  template:
    metadata:
      labels:
        app: mcode-site
    spec:
      containers:
      - name: mcode-site
        image: docker.io/ligulfzhou53/mcode-site
        imagePullPolicy: Always
        env:
          - name: ContractAddress
            value: "0x9c886f1e9c25b35573f31129182fcff92198cd9a"
        ports:
        - containerPort: 3000
